@extends('layouts.admin')
@section('title', 'Manajemen Testimoni - SportZ')
@section('content')
<div class="space-y-6">
    <div class="flex items-center justify-between"><h1 class="font-heading text-2xl font-bold text-gray-900 dark:text-white">Manajemen Testimoni</h1><button onclick="document.getElementById('testiModal').classList.remove('hidden')" class="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl hover:shadow-lg transition-all"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg> Tambah</button></div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        @forelse($testimonials as $testi)
        <div class="bg-white dark:bg-gray-800/50 rounded-2xl p-6 border border-gray-100 dark:border-gray-700/50">
            <div class="flex items-center gap-1 mb-3">@for($i = 1; $i <= 5; $i++)<svg class="w-4 h-4 {{ $i <= $testi->rating ? 'text-yellow-400' : 'text-gray-300' }}" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>@endfor</div>
            <p class="text-sm text-gray-600 dark:text-gray-400 italic mb-4">"{{ Str::limit($testi->content, 120) }}"</p>
            <div class="flex items-center justify-between">
                <div class="flex items-center gap-2"><div class="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center text-white text-xs font-bold">{{ substr($testi->name, 0, 1) }}</div><div><p class="text-sm font-semibold text-gray-900 dark:text-white">{{ $testi->name }}</p><p class="text-xs text-gray-500">{{ $testi->role }}</p></div></div>
                <form action="{{ route('admin.testimonials.destroy', $testi->id) }}" method="POST" onsubmit="return confirm('Hapus?')">@csrf @method('DELETE')<button class="text-red-500 text-xs hover:underline">Hapus</button></form>
            </div>
        </div>
        @empty<div class="col-span-full"><x-empty-state title="Belum ada testimoni" /></div>@endforelse
    </div>
    {{ $testimonials->links() }}
</div>
<div id="testiModal" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"><div class="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md mx-4 shadow-2xl"><div class="flex items-center justify-between mb-4"><h3 class="font-heading text-lg font-bold">Tambah Testimoni</h3><button onclick="document.getElementById('testiModal').classList.add('hidden')" class="text-gray-400">✕</button></div><form action="{{ route('admin.testimonials.store') }}" method="POST" class="space-y-4">@csrf<div><label class="block text-sm font-medium mb-1">Nama *</label><input type="text" name="name" required class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div><label class="block text-sm font-medium mb-1">Jabatan</label><input type="text" name="role" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div><label class="block text-sm font-medium mb-1">Isi Testimoni *</label><textarea name="content" rows="3" required class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500 resize-none"></textarea></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium mb-1">Rating</label><select name="rating" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"><option value="5">⭐⭐⭐⭐⭐</option><option value="4">⭐⭐⭐⭐</option><option value="3">⭐⭐⭐</option></select></div><div class="flex items-end"><label class="flex items-center gap-2 pb-2"><input type="checkbox" name="is_active" value="1" checked class="rounded text-cyan-500"><span class="text-sm">Aktif</span></label></div></div><button type="submit" class="w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl">Simpan</button></form></div></div>
@endsection
