@extends('layouts.admin')
@section('title', 'Manajemen FAQ - SportZ')
@section('content')
<div class="space-y-6">
    <div class="flex items-center justify-between"><h1 class="font-heading text-2xl font-bold text-gray-900 dark:text-white">Manajemen FAQ</h1><button onclick="document.getElementById('faqModal').classList.remove('hidden')" class="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl hover:shadow-lg transition-all"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg> Tambah FAQ</button></div>
    <div class="space-y-3">
        @forelse($faqs as $faq)
        <div class="bg-white dark:bg-gray-800/50 rounded-2xl p-5 border border-gray-100 dark:border-gray-700/50 flex items-start justify-between gap-4">
            <div class="flex-1"><h3 class="font-semibold text-gray-900 dark:text-white mb-1">{{ $faq->question }}</h3><p class="text-sm text-gray-500 dark:text-gray-400">{{ Str::limit($faq->answer, 150) }}</p><div class="flex gap-2 mt-2"><span class="text-xs text-gray-400">Sort: {{ $faq->sort_order }}</span><span class="text-xs {{ $faq->is_active ? 'text-green-500' : 'text-red-500' }}">{{ $faq->is_active ? 'Aktif' : 'Nonaktif' }}</span></div></div>
            <form action="{{ route('admin.faqs.destroy', $faq->id) }}" method="POST" onsubmit="return confirm('Hapus FAQ ini?')">@csrf @method('DELETE')<button class="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors"><svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg></button></form>
        </div>
        @empty<x-empty-state title="Belum ada FAQ" />@endforelse
    </div>
    {{ $faqs->links() }}
</div>
<div id="faqModal" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"><div class="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-lg mx-4 shadow-2xl"><div class="flex items-center justify-between mb-4"><h3 class="font-heading text-lg font-bold text-gray-900 dark:text-white">Tambah FAQ</h3><button onclick="document.getElementById('faqModal').classList.add('hidden')" class="text-gray-400 hover:text-gray-600">✕</button></div><form action="{{ route('admin.faqs.store') }}" method="POST" class="space-y-4">@csrf<div><label class="block text-sm font-medium mb-1">Pertanyaan *</label><input type="text" name="question" required class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div><label class="block text-sm font-medium mb-1">Jawaban *</label><textarea name="answer" rows="4" required class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500 resize-none"></textarea></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium mb-1">Urutan</label><input type="number" name="sort_order" value="0" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div class="flex items-end"><label class="flex items-center gap-2 pb-2"><input type="checkbox" name="is_active" value="1" checked class="rounded text-cyan-500"><span class="text-sm">Aktif</span></label></div></div><button type="submit" class="w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl">Simpan</button></form></div></div>
@endsection
