@extends('layouts.admin')
@section('title', 'Manajemen Banner - SportZ')
@section('content')
<div class="space-y-6">
    <div class="flex items-center justify-between"><h1 class="font-heading text-2xl font-bold text-gray-900 dark:text-white">Manajemen Banner</h1><button onclick="document.getElementById('bannerModal').classList.remove('hidden')" class="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl hover:shadow-lg transition-all"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg> Tambah</button></div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        @forelse($banners as $banner)
        <div class="bg-white dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-700/50 overflow-hidden"><div class="h-40 bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center"><span class="text-white text-xl font-bold">{{ $banner->title }}</span></div><div class="p-4 flex items-center justify-between"><div><p class="font-semibold text-gray-900 dark:text-white text-sm">{{ $banner->title }}</p><p class="text-xs text-gray-500">Sort: {{ $banner->sort_order }} • {{ $banner->is_active ? 'Aktif' : 'Nonaktif' }}</p></div><form action="{{ route('admin.banners.destroy', $banner->id) }}" method="POST" onsubmit="return confirm('Hapus?')">@csrf @method('DELETE')<button class="text-red-500 text-sm hover:underline">Hapus</button></form></div></div>
        @empty<div class="col-span-full"><x-empty-state title="Belum ada banner" /></div>@endforelse
    </div>
</div>
<div id="bannerModal" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"><div class="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md mx-4 shadow-2xl"><div class="flex items-center justify-between mb-4"><h3 class="font-heading text-lg font-bold text-gray-900 dark:text-white">Tambah Banner</h3><button onclick="document.getElementById('bannerModal').classList.add('hidden')" class="text-gray-400 hover:text-gray-600">✕</button></div><form action="{{ route('admin.banners.store') }}" method="POST" enctype="multipart/form-data" class="space-y-4">@csrf<div><label class="block text-sm font-medium mb-1">Judul *</label><input type="text" name="title" required class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div><label class="block text-sm font-medium mb-1">Gambar</label><input type="file" name="image" accept="image/*" class="w-full text-sm"></div><div><label class="block text-sm font-medium mb-1">Link</label><input type="text" name="link" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium mb-1">Urutan</label><input type="number" name="sort_order" value="0" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 focus:ring-2 focus:ring-cyan-500"></div><div class="flex items-end"><label class="flex items-center gap-2 pb-2"><input type="checkbox" name="is_active" value="1" checked class="rounded text-cyan-500"><span class="text-sm">Aktif</span></label></div></div><button type="submit" class="w-full py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-xl">Simpan</button></form></div></div>
@endsection
